### ISSUE TITLE
Add the initial list of EditorConfig properties.

### ISSUE THREAD

**Issue by ppalaga** [ec4j/editorconfig-java-domain#1]
As mentioned in https://github.com/editorconfig/editorconfig/issues/381#issuecomment-440349307 @dyadix has a list of EditorConfig properties releavant to java. Let's add it into this repo in form of a commented .editorconfig file. Initially, the list does not need to contain any textual explanation what the individual properties do, we will fix that later.

**Comment by ppalaga** [comment]
@dyadix it is perhaps a good idea to put them into three separate files `general.editorconfig`, `c-like.editorconfig` and `java.editorconfig`.

**Comment by dyadix** [comment]
@ppalaga I have added the files with properties as you suggested. I also wrote descriptions for some of them as an example. In addition added "java_" prefix to all java-specific properties vs common c-like languages' properties. Please let me know if the format is OK, I will continue adding more descriptions then.

**Comment by ppalaga** [comment]
@dyadix great, thanks!

Please, let's send changes via GitHub pull requests so that they can be discussed/improved before they are merged. I'll be doing the same with my changes asking you for an approval before merge.

Also let's stick to a convention to have commit messages like the following so that a pull request merge auto closes the fixed issue:

  Fix #{n} {issueTitle}

where `{n}` is the number of the issue and `{issueTitle}` is preferably the title of the fixed issue.

**Comment by dyadix** [comment]
Sure, I will! Any further changes to the list will be done as you have described.
