### ISSUE TITLE
Minimal test for IntelliJ formatter

### ISSUE THREAD

**Issue by ppalaga** [ec4j/editorconfig-java-domain#2]
@dyadix as I said earlier, I'd like to setup a CI to test the compatibility of the formatters with the spec. I know how to do this for JDT, but I'd need your help how to do that for IJ. 

I have set up [ij-formatter-build repo](https://github.com/ppalaga/ij-formatter-build/) to do this. It builds IJ from sources (in `target/ij` directory) and it contains a [test stub](https://github.com/ppalaga/ij-formatter-build/blob/master/src/test/java/org/ec4j/linters/ij/IjFormatterTest.java#L19) that needs to be completed. 

I tried myself but could come up with any working solution. I suspect the test needs to invoke `CodeFormatterFacade.processText(PsiFile file, final FormatTextRanges ranges, boolean doPostponedFormatting)` but I could not figure out how to setup the PsiFile, Project, etc. Maybe this is easy for you? Could you please send a PR against https://github.com/ppalaga/ij-formatter-build that adds the missing bits?

**Comment by ppalaga** [comment]
BTW, there is a TravisCI hook for the repo. Here is the latest build https://travis-ci.org/ppalaga/ij-formatter-build/builds/458942197 The test compiles, which proves that `CodeFormatterFacade` is visible in the test.

**Comment by dyadix** [comment]
It's more complicated than that. Currently there is a script `format.sh` for Linux/OSX and `format.bat` for Windows. It actually invokes command-line formatter which sets up a project and etc. Yes, I'm familiar with all that stuff and I'll take a look. But it will take some time an

**Comment by ppalaga** [comment]
#4 in its currently proposed form anticipates that we create an IJ implementation of (https://github.com/ec4j/editorconfig-java-domain/blob/3ed1b92eb72ac2661473a97633ecca00a54dd53f/tck-spi/src/main/java/org/ec4j/java/domain/tck/spi/Formatter.java) much like the one I created for JDT in [jdt Maven module](https://github.com/ec4j/editorconfig-java-domain/tree/3ed1b92eb72ac2661473a97633ecca00a54dd53f/jdt).

I tried to keep the (https://github.com/ec4j/editorconfig-java-domain/blob/3ed1b92eb72ac2661473a97633ecca00a54dd53f/tck-spi/src/main/java/org/ec4j/java/domain/tck/spi/Formatter.java) interface as simple as possible, so that it also allows for calling a command line tool. So if there is no better way to call the IJ formatter, we can use also `format.[sh|bat]`. 

Calling `format.[sh|bat]` is not ideal, because one has to build a complete IJ distro for that which costs a lot of time. I hoped that with a plain Java solution, I'd be able to exclude a part of the IJ classes from compilation so that our (editorconfig-java-domain) CI can run faster. 

Clearly, having all necessary IJ code released to a public Maven repo would be ideal, but looking at the current IJ source tree, such thing seems to be technically/politically hard to dream about.

That said, we can start with `format.[sh|bat]` but any movement away from it towards a piece of Java code depending on IJ jars either pulled from a Maven repo or built locally is highly welcome.
