### ISSUE TITLE
IntelliJ's `format[sh|bat]` ignores `.editorconfig`

### ISSUE THREAD

**Issue by ppalaga** [ec4j/editorconfig-java-domain#5]
Needs to be fixed in IJ, as reported by @dyadix https://github.com/ec4j/editorconfig-java-domain/pull/4#pullrequestreview-186655507

**Comment by dyadix** [comment]
@ppalaga I found out that IntelliJ formatter actually works with .editorconfig when launched from a command line but for some reason .editorconfig file is missing from `/tmp/IjFormatter<...>/src/..` directory with a source file. Is it some kind of a bug in a test launcher script? Could you please check it?

**Comment by ppalaga** [comment]
> .editorconfig file is missing from `/tmp/IjFormatter<...>/src/..`

Thanks for the hint! Let me check.
